### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ubx** [ubx/meta-glide#1]
- [x] Setup a todo list
- [x] XCSoar: start on boot
- [x] XCSoar: CAN device menu, remove speed setting 
- [x] XCSoar: investigate map jitter
- [x] glide: test on Display L hardware
- [x] glide: create a mini maintenance menu
- [x] glide: maintenance menu: upload XCSoar site files
- [x] glide: maintenance menu: update XCSoar 
- [ ] glide: maintenance menu: download igc files from vario
- [ ] glide: maintenance better menu
- [ ] glide: detect idle and lower backlight power

**Comment by markus2marks** [comment]
Good idea to add the Can interface to xcsoar. I integrated your code into the current branch to test it with a Raspberry Pi. It works, but some features are missing from your code, such as the horizon (which I already added) or downloading the flight from the logger. Do you have any information about how the protocol works to transfer the files to xcsoar?

**Comment by ubx** [comment]
> I integrated your code into the current branch to test it with a Raspberry Pi. 
> It works, but some features are missing from your code, such as the horizon (which I already added).

Can you share your code?


> Do you have any information about how the protocol works to transfer the files to xcsoar?

If you mean downloading IGC file via CAN interface: not yet, but I'll contact the manufacturer of the Sensor Unit (where the logger is build in).

**Comment by markus2marks** [comment]
my code: https://github.com/markus2marks/XCSoar/tree/canaerospace. I have a bug. When I start xcsoar, the CAN interface does not start automatically. I have to restart the configuration, then it works. Do you have the same problem?

Yes, it would be a cool feature to be able to download IGC files to xcsoar.

**Comment by ubx** [comment]
> I have a bug. When I start xcsoar, the CAN interface does not start automatically. 

Before running XCSoar, the [run_xcsoar.sh](https://github.com/ubx/meta-glide/blob/master/oe-core/layers/meta-glide/recipes-xcsoar/xcsoar/files/run_xcsoar.sh)  script sets up the CAN interface:
```
### start can device
ip link set can0 type can bitrate 500000
ip link set can0 txqueuelen 1000
ip link set can0 up
```

**Comment by markus2marks** [comment]
i know  and i'm calling it befor xcsoar starts. I think thats not the problem... When I enter “candump can0” in the console, I immediately see the messages from can0. I think there is a problem in xcsoar.

**Comment by markus2marks** [comment]
Do you have any news about the protocol?
I am working on the Larus Vario at the moment and I have some ideas about how I could use my air glide Vario display in the future. I’m thinking about using the regular CAN connector on the Larus sensor board. On the software side, I want to integrate CANaerospace. 

<img width="919" height="454" alt="Image" src="https://github.com/user-attachments/assets/15b59bfa-df2a-4515-a9d1-e7bfd88a3f87" />

**Comment by ubx** [comment]
> Do you have any news about the protocol?

I assume you’re referring to downloading IGC files to XCSoar. I talked to the manufacturer of the Display-S (aka Vario), but he was not willing or able to describe the protocol or provide the source code. I’ll ask him again.

In the meantime, I’ve extended my custom [XCSoar build](https://github.com/ubx/XCSoar/tree/can-bus-with-canaerospace)
so it understands SLCAN messages, meaning it can receive CAN messages over USB using devices like the [CANable](https://canable.io/). This enables connecting the Display-S and AIR Glide Sensor Unit to an Android device (phone, tablet, SteFly Nav, etc.).

I also created a [CAN-to-SLCAN with Filter](https://github.com/ubx/CAN-to-SLCAN-with-filter) device. The software is tested and working; only the 3D-printed case is still in progress.

In our glider, we plan to replace the Display-L with either a SteFly NAV or an XCNAV. With the hardware and software above, it should work with all CAN devices.

**Comment by markus2marks** [comment]
Ok, thanks for your feedback. I still don't understand why he doesn't want to share the protocol explanation with us. But if you want, feel free to ask him again :D
